# Generated by Django 2.0.2 on 2018-03-06 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Jitai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jitai_id', models.CharField(default='.', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('question_description', models.CharField(default='.', max_length=500)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Yazhu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='date published')),
                ('work_prod', models.CharField(default='.', max_length=50, verbose_name='产品')),
                ('work_by', models.CharField(default='.', max_length=50, verbose_name='操作员')),
                ('work_support', models.CharField(default='.', max_length=50, verbose_name='技术员')),
                ('work_leader', models.CharField(default='.', max_length=50, verbose_name='班组长')),
                ('work_qtyall', models.CharField(default='.', max_length=50, verbose_name='数量')),
                ('work_qtyok', models.CharField(default='.', max_length=50, verbose_name='良品数量')),
                ('work_rej', models.CharField(default='.', max_length=50, verbose_name='不良数量')),
                ('work_rejper', models.CharField(default='.', max_length=50, verbose_name='不良率')),
                ('rej01', models.IntegerField(default=0, verbose_name='欠铸')),
                ('rej02', models.IntegerField(default=0, verbose_name='沙孔')),
                ('rej03', models.IntegerField(default=0, verbose_name='气泡')),
                ('rej04', models.IntegerField(default=0, verbose_name='拉伤')),
                ('rej05', models.IntegerField(default=0, verbose_name='冲蚀')),
                ('rej06', models.IntegerField(default=0, verbose_name='表面裂纹')),
                ('rej07', models.IntegerField(default=0, verbose_name='顶针凹/凸')),
                ('rej08', models.IntegerField(default=0, verbose_name='变形')),
                ('rej09', models.IntegerField(default=0, verbose_name='毛刺')),
                ('rej10', models.IntegerField(default=0, verbose_name='尺寸不良')),
                ('rej11', models.IntegerField(default=0, verbose_name='其他')),
                ('work_mach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Jitai')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
