# Generated by Django 2.0.2 on 2018-03-06 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JitaiXX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jitaixx_id', models.CharField(default='.', max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='yazhu',
            name='work_mach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.JitaiXX'),
        ),
    ]
