# Generated by Django 2.0.2 on 2018-03-06 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180306_0955'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jitai',
        ),
    ]
