# Generated by Django 2.0.2 on 2018-03-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_delete_jitai'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jitai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jitai_id', models.CharField(default='.', max_length=2000)),
            ],
        ),
    ]
