# Generated by Django 2.0.2 on 2018-03-06 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_jitai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazhu',
            name='work_mach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Jitai'),
        ),
        migrations.DeleteModel(
            name='JitaiXX',
        ),
    ]
