# Generated by Django 2.0.2 on 2018-04-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180306_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(default='.', max_length=50, verbose_name='组别')),
                ('empe_id', models.CharField(default='.', max_length=2000, verbose_name='工号')),
                ('empe_name', models.CharField(default='.', max_length=2000, verbose_name='姓名')),
                ('empe_dept', models.CharField(default='.', max_length=2000, verbose_name='部门')),
                ('tel', models.CharField(default='.', max_length=2000, verbose_name='手机号码')),
            ],
        ),
    ]
