# Generated by Django 2.0.1 on 2018-01-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_yazhu_work_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='yazhu',
            name='work_leader',
            field=models.CharField(default='.', max_length=50),
        ),
        migrations.AddField(
            model_name='yazhu',
            name='work_qty',
            field=models.CharField(default='.', max_length=50),
        ),
        migrations.AddField(
            model_name='yazhu',
            name='work_qty1',
            field=models.CharField(default='.', max_length=50),
        ),
        migrations.AddField(
            model_name='yazhu',
            name='work_rej',
            field=models.CharField(default='.', max_length=50),
        ),
        migrations.AddField(
            model_name='yazhu',
            name='work_rejper',
            field=models.CharField(default='.', max_length=50),
        ),
        migrations.AddField(
            model_name='yazhu',
            name='work_support',
            field=models.CharField(default='.', max_length=50),
        ),
    ]
