# Generated by Django 2.0.1 on 2018-01-11 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20180111_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yazhu',
            old_name='work_qty',
            new_name='work_qtyall',
        ),
        migrations.RenameField(
            model_name='yazhu',
            old_name='work_qty1',
            new_name='work_qtyok',
        ),
    ]
