# Generated by Django 2.0.1 on 2018-01-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20180111_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='yazhu',
            name='rej04',
            field=models.IntegerField(default=0, verbose_name='拉伤'),
        ),
        migrations.AddField(
            model_name='yazhu',
            name='rej05',
            field=models.IntegerField(default=0, verbose_name='冲蚀'),
        ),
        migrations.AddField(
            model_name='yazhu',
            name='rej06',
            field=models.IntegerField(default=0, verbose_name='表面裂纹'),
        ),
        migrations.AddField(
            model_name='yazhu',
            name='rej07',
            field=models.IntegerField(default=0, verbose_name='顶针凹/凸'),
        ),
        migrations.AddField(
            model_name='yazhu',
            name='rej08',
            field=models.IntegerField(default=0, verbose_name='变形'),
        ),
        migrations.AddField(
            model_name='yazhu',
            name='rej09',
            field=models.IntegerField(default=0, verbose_name='毛刺'),
        ),
        migrations.AddField(
            model_name='yazhu',
            name='rej10',
            field=models.IntegerField(default=0, verbose_name='尺寸不良'),
        ),
        migrations.AddField(
            model_name='yazhu',
            name='rej11',
            field=models.IntegerField(default=0, verbose_name='其他'),
        ),
        migrations.AlterField(
            model_name='yazhu',
            name='rej01',
            field=models.IntegerField(default=0, verbose_name='欠铸'),
        ),
        migrations.AlterField(
            model_name='yazhu',
            name='rej02',
            field=models.IntegerField(default=0, verbose_name='沙孔'),
        ),
        migrations.AlterField(
            model_name='yazhu',
            name='rej03',
            field=models.IntegerField(default=0, verbose_name='气泡'),
        ),
        migrations.AlterField(
            model_name='yazhu',
            name='work_by',
            field=models.CharField(default='.', max_length=50, verbose_name='操作员'),
        ),
        migrations.AlterField(
            model_name='yazhu',
            name='work_leader',
            field=models.CharField(default='.', max_length=50, verbose_name='班组长'),
        ),
        migrations.AlterField(
            model_name='yazhu',
            name='work_mach',
            field=models.CharField(default='.', max_length=50, verbose_name='机台'),
        ),
        migrations.AlterField(
            model_name='yazhu',
            name='work_prod',
            field=models.CharField(default='.', max_length=50, verbose_name='产品'),
        ),
        migrations.AlterField(
            model_name='yazhu',
            name='work_qtyall',
            field=models.CharField(default='.', max_length=50, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='yazhu',
            name='work_qtyok',
            field=models.CharField(default='.', max_length=50, verbose_name='良品数量'),
        ),
        migrations.AlterField(
            model_name='yazhu',
            name='work_rej',
            field=models.CharField(default='.', max_length=50, verbose_name='不良数量'),
        ),
        migrations.AlterField(
            model_name='yazhu',
            name='work_rejper',
            field=models.CharField(default='.', max_length=50, verbose_name='不良率'),
        ),
        migrations.AlterField(
            model_name='yazhu',
            name='work_support',
            field=models.CharField(default='.', max_length=50, verbose_name='技术员'),
        ),
    ]
