# Generated by Django 2.0.2 on 2018-02-27 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20180208_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jitai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jitai_id', models.CharField(max_length=200)),
                ('jitai_description', models.CharField(default='.', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='yazhu',
            name='work_mach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
