# Generated by Django 2.0.2 on 2018-02-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20180227_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='jitai',
            name='pub_date',
            field=models.DateTimeField(default=1, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
