# Generated by Django 2.0.2 on 2018-02-27 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_jitai_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jitai',
            name='pub_date',
        ),
    ]
