# Generated by Django 2.0.2 on 2018-02-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_remove_jitai_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jitai',
            name='jitai_id',
            field=models.CharField(default='.', max_length=200),
        ),
    ]
