# Generated by Django 2.0.2 on 2018-03-06 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20180227_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jitai',
            old_name='jitai_id',
            new_name='jitai',
        ),
        migrations.RemoveField(
            model_name='jitai',
            name='jitai_description',
        ),
    ]
