# Generated by Django 2.0.2 on 2018-03-06 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20180306_0825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jitai',
            old_name='jitai',
            new_name='jitai_id',
        ),
    ]
